### ISSUE TITLE
BlueCove on Windows 7 x64

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#109]
```
Hello! I'm using BlueCove 2.1.0 on Windows 7 Ultimate x64. I'm getting a 
BluetoothStateException at the very beginning of my code (Initialization).
The initialization rutine is:

 try
        {
              LocalDev = LocalDevice.getLocalDevice();
              LocalDev.setDiscoverable(DiscoveryAgent.GIAC);
              StreamNotif = 
(StreamConnectionNotifier)Connector.open(strUrl);
              StreamCon = StreamNotif.acceptAndOpen();
              InitServer = true;
              Output = StreamCon.openOutputStream();
              Input = StreamCon.openInputStream();
        }
        catch (BluetoothStateException e)
        {
            System.err.println( "BluetoothStateException: " + 
e.getMessage() );
        }
        catch (IOException ex)
        {
            ex.printStackTrace();
        }
        catch(Exception e)
        {
            System.err.println( "Exception: " + e.getMessage() );
        }



And the output is:

run:
Native Library intelbth_x64 not available
Native Library bluecove_x64 not available
BluetoothStateException: BlueCove libraries not available




Is there any way to solve this? Does BlueCove runs only on x32 based 
systems? Thanks a lot! Bye.-

```

Original issue reported on code.google.com by `nachomontamat@gmail.com` on 1 May 2010 at 6:25

**Comment by GoogleCodeExporter** [comment]
```
i have the same problem. :(
```

Original comment by `Pvt.Vent...@gmail.com` on 7 May 2010 at 2:35

**Comment by GoogleCodeExporter** [comment]
```
same problem here
```

Original comment by `basic.do...@gmail.com` on 16 May 2010 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
Could someone build BlueCove intelbth_x64.dll and bluecove_x64.dll for windows 
if thats 
posible? Was really confused by my app working in netbeans but not from command 
line, 
and not from a launch4j wrapper/launcher.
```

Original comment by `Jamedjo` on 17 May 2010 at 11:46

**Comment by GoogleCodeExporter** [comment]
```
Nevermind... found that the latest (1st April) SNAPSHOT build the intel 64bit 
dll 
included. It didn't get the "Native Library intelbth_x64 not available/Native 
Library 
bluecove_x64 not available" error and appears to work.

http://snapshot.bluecove.org/distribution/download/2.1.1-SNAPSHOT/2.1.1-
SNAPSHOT.61/bluecove-2.1.1-SNAPSHOT.jar
```

Original comment by `Jamedjo` on 17 May 2010 at 12:03

**Comment by GoogleCodeExporter** [comment]
```
Solution: use this 
http://snapshot.bluecove.org/distribution/download/2.1.1-SNAPSHOT/2.1.1-SNAPSHOT
.62/
```

Original comment by `marcoso...@gmail.com` on 29 May 2010 at 5:12

**Comment by GoogleCodeExporter** [comment]
```
Thanx
```

Original comment by `amie.vis...@gmail.com` on 6 Jun 2010 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
I have received a similar error on Windows 7 x64. Using the latest snapshot, 
the intelbth_x64 error has gone but the bluecove_x64 error persists.

The code is 

import java.io.IOException;
import java.util.Vector;
import javax.bluetooth.*;

/**
 * Minimal Device Discovery example.
 */
public class RemoteDeviceDiscovery {

    public static final Vector/*<RemoteDevice>*/ devicesDiscovered = new Vector();

    public static void main(String[] args) throws IOException, InterruptedException {

        final Object inquiryCompletedEvent = new Object();

        devicesDiscovered.clear();

        DiscoveryListener listener = new DiscoveryListener() {

            public void deviceDiscovered(RemoteDevice btDevice, DeviceClass cod) {
                System.out.println("Device " + btDevice.getBluetoothAddress() + " found");
                devicesDiscovered.addElement(btDevice);
                try {
                    System.out.println("     name " + btDevice.getFriendlyName(false));
                } catch (IOException cantGetDeviceName) {
                }
            }

            public void inquiryCompleted(int discType) {
                System.out.println("Device Inquiry completed!");
                synchronized(inquiryCompletedEvent){
                    inquiryCompletedEvent.notifyAll();
                }
            }

            public void serviceSearchCompleted(int transID, int respCode) {
            }

            public void servicesDiscovered(int transID, ServiceRecord[] servRecord) {
            }
        };

        synchronized(inquiryCompletedEvent) {
            boolean started = LocalDevice.getLocalDevice().getDiscoveryAgent().startInquiry(DiscoveryAgent.GIAC, listener);
            if (started) {
                System.out.println("wait for device inquiry to complete...");
                inquiryCompletedEvent.wait();
                System.out.println(devicesDiscovered.size() +  " device(s) found");
            }
        }
    }

}

Native Library bluecove_x64 not available
Exception in thread "main" javax.bluetooth.BluetoothStateException: BlueCove 
library bluecove not available;
resource not found bluecove_x64.dll
load [bluecove_x64] no bluecove_x64 in java.library.path
        at com.intel.bluetooth.BlueCoveImpl.loadNativeLibraries(BlueCoveImpl.java:396)
        at com.intel.bluetooth.BlueCoveImpl.setBluetoothStack(BlueCoveImpl.java:963)
        at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:502)
        at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)
        at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1044)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.java:1042)
        at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack(BlueCoveImpl.java:1035)
        at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:75)
        at javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:95)
        at iilserverapp.RemoteDeviceDiscovery.main(RemoteDeviceDiscovery.java:55)
Java Result: 1
```

Original comment by `sais...@gmail.com` on 9 Jun 2010 at 6:44

**Comment by GoogleCodeExporter** [comment]
```
Hey guys, its working rite now. Just restarted the jvm and its working... Dont 
know how but. 
```

Original comment by `sais...@gmail.com` on 12 Jun 2010 at 9:44

**Comment by GoogleCodeExporter** [comment]
```
I am still getting the error with bluecove_x64 not existing.  I extracted the 
jar and don't see it there in the latest snapshot.  Anyone have it?
```

Original comment by `xpdolp...@gmail.com` on 1 Jul 2010 at 5:41

**Comment by GoogleCodeExporter** [comment]
```
I have added only MS stack support on Win64 (intelbth_x64)
http://snapshot.bluecove.org/distribution/download/2.1.1-SNAPSHOT/2.1.1-SNAPSHOT
.62/

For Widcomm bluecove_x64) more work needs to be done.
```

Original comment by `skarzhev...@gmail.com` on 26 Jul 2010 at 4:59

**Comment by GoogleCodeExporter** [comment]
```
Is it on the main TODO list to get Widcomm 64-bit working?  My bluetooth 
adapter doesn't seem to play nice with the MS stack in Java.  Thanks for the 
update.
```

Original comment by `xpdolp...@gmail.com` on 27 Jul 2010 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
This thread is obviously old but the issue is still important. Is there a 
possibility to get bluecove run with widcomm on a windows 7 x64 system? The 
current snapshot still does not contain the bluecove_x64.dll.
```

Original comment by `arnd.e...@googlemail.com` on 13 Jan 2011 at 5:34

**Comment by GoogleCodeExporter** [comment]
```
Indeed, the latest build (63) does *not* include the needed bluecove_x64.dll, 
only the intelbth_x64.dll is there. Win 7, x64 as well, any help please ?
```

Original comment by `pitu.cos...@gmail.com` on 15 Jan 2011 at 12:10

**Comment by GoogleCodeExporter** [comment]
```
What (if any) can we do to get the bluecove_x64.dll faster?
```

Original comment by `hjall...@gmail.com` on 21 Jan 2011 at 4:28

**Comment by GoogleCodeExporter** [comment]
```
I am facing the same problem. How to include bluecove_x64.dll? Any suggestions, 
please?
```

Original comment by `kalpspu...@gmail.com` on 11 Feb 2011 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
I am able to use the 32-bit version in an 64-bit Mac OS X machine by including 
-d32 in the vm arguments. I haven't tried it on a Windows machine, though. 

I'd love to see progress on bluecove_x64.dll, but in the meantime could you try 
this workaround and see if it works in Windows as well? 

```

Original comment by `gazialan...@gmail.com` on 11 Feb 2011 at 3:52

**Comment by GoogleCodeExporter** [comment]
```
Well.. I put -d32 in vm arguments and it said "cannot create java virtual 
machine". And th output is "Unrecognized option: d32". 


```

Original comment by `kalpspu...@gmail.com` on 12 Feb 2011 at 7:17

**Comment by GoogleCodeExporter** [comment]
```
"For Widcomm bluecove_x64) more work needs to be done." Can you please tell 
what more work in specific?
```

Original comment by `kalpspu...@gmail.com` on 12 Feb 2011 at 7:33

**Comment by GoogleCodeExporter** [comment]
```
@ kalpspu...@gmail.com    Try -D32 instead of -d32
```

Original comment by `grobme...@gmail.com` on 6 Apr 2011 at 10:19

**Comment by GoogleCodeExporter** [comment]
```
I have been using this library with a windows 7 x64 too so far no problems with 
initialization and device discovery, but when I try to actually transfer data 
using rfcomm there's no data interchange...
```

Original comment by `rocket18...@gmail.com` on 27 Apr 2011 at 2:52

**Comment by GoogleCodeExporter** [comment]
```
Hi guys, are there same news about this problem?

I need to work with WIDCOMM on windows 7 64 bit.

I am using the last build bluecove-2.1.1-SNAPSHOT.jar, but I still get the error

Native Library bluecove_x64 not available

so I suppose that the .DLL compatible with WIDCOMM is not include in that build.

I tried the option -D32 when running Java ma it did not solve the problem.

Any suggestions?
```

Original comment by `diego.be...@gmail.com` on 3 Aug 2011 at 3:36

**Comment by GoogleCodeExporter** [comment]
```
Hi Friends,

So here is the problem I am stuck at
- First of all, I am running Windows 7 Enterprise (64 bit).
- I downloaded the sameple Bluetooth Server demo available at 
http://luugiathuy.com/2011/02/android-java-bluetooth/
- I got the exceptions as mentioned in the comments above, about the library 
not available
- As suggested, I downloaded the bluecove-2.1.1-SNAPSHOT.jar and 
bluecove-gpl-2.1.1-SNAPSHOT.jar, which resolved the issues

Now, I tried connecting but was stuck. I see that the server is just stuck at 
acceptAndOpen(). No warnings, no exceptions. Any connection to the server from 
Client are not handled.


Can anyone suggest what can possibly be wrong?

I have been able to work with the usual bluetooth connection between my 
Broadcom adapter on Thinkpad T61 and My Samsung Galaxy running Android 2.3. So 
I can rule out any compatibility issues between them.

Waiting for inputs/suggestions.

Thanks !
```

Original comment by `ujjwal.w...@gmail.com` on 16 Aug 2011 at 3:15

**Comment by GoogleCodeExporter** [comment]
```
All right, I found the solution to my own problem. It turns out that you have 
to pair the device (Samsung Captivate in my case) to the laptops default 
Bluetooth appliation. Once I paired the device (entering the four 0000s stuff), 
I was able to get past the acceptAndOpen() stuck issue. Now my connections 
works.

So, essentially Windows 7 64bit works with the SNAPSHOT jar


```

Original comment by `ujjwal.w...@gmail.com` on 16 Aug 2011 at 5:28

**Comment by GoogleCodeExporter** [comment]
```
Hi,
even using the latest 2.1.1 snapshot, in my application bluecove seems not 
working on Windows 7 64 bit. It can discover the device, but I can connect to 
it. I get the exception:
Connection failed. Try again.
javax.bluetooth.BluetoothConnectionException: Failed to Connect
        at com.intel.bluetooth.BluetoothStackWIDCOMM.l2OpenClientConnectionImpl(
Native Method)
        at com.intel.bluetooth.BluetoothStackWIDCOMM.l2OpenClientConnection(Blue
toothStackWIDCOMM.java:915)
        at com.intel.bluetooth.BluetoothL2CAPClientConnection.<init>(BluetoothL2
CAPClientConnection.java:35)
        at com.intel.bluetooth.MicroeditionConnector.openImpl(MicroeditionConnec
tor.java:407)
        at com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.
java:535)
I am using the WIDCOMM drivers and the L2CAP protocol. These requirements are 
mandatory, because my device requires L2CAP and to my knowledge WIDCOMM is the 
only windows-compatible bluetooth stack that supports L2CAP.

Perhaps the problems is that the snapshot does not include bluecove_x64.dll?

Can I force the JVM execution to 32 bit?

Any suggestions?!
```

Original comment by `diego.be...@gmail.com` on 12 Oct 2011 at 1:45

**Comment by GoogleCodeExporter** [comment]
```
I use windows 7 32 bit and netbeans 7.1
I'm trying to make an application client (J2SE) server (J2ME) only when I do on 
the server
private static final UUID uuid =
             new UUID ("F0E0D0C0B0A000908070605040302010", false);
String url = "btspp :/ / localhost:" + uuid.toString () + ", name = Picture 
Server; authorize = false";
notifier = (StreamConnectionNotifier) Connector.open (url.toString ());
notifier.acceptAndOpen conn = ();

and then try to find the client server, it does not find, ie the server is 
stopped notifier.acceptAndOpen (), and the client does not display any error
On the server I added only bluecove-2.1.1-SNAPSHOT.jar
Any idea what it's been several days can not progress
Sorry my poor english
```

Original comment by `tiagojos...@gmail.com` on 2 Mar 2012 at 3:18

**Comment by GoogleCodeExporter** [comment]
```
Awesome, downloading the latest snapshot did the trick :-)
```

Original comment by `cbhav...@uci.edu` on 9 Mar 2012 at 1:34

**Comment by GoogleCodeExporter** [comment]
```
I have the same Window7 64-bit issues.

a la:
>>Native Library intelbth_x64 not available
>>Native Library bluecove_x64 not available
>>BluetoothStateException: BlueCove libraries not available

Solution:
Downloading and adding the JARs to my project resolved the issue.
http://snapshot.bluecove.org/distribution/download/2.1.1-SNAPSHOT/2.1.1-SNAPSHOT
.62/

Thanks.
```

Original comment by `dducr...@gmail.com` on 28 Mar 2012 at 11:28

**Comment by GoogleCodeExporter** [comment]
```
Thanks.snapshot 2.1.1 worked for me
```

Original comment by `mamun.b...@gmail.com` on 20 Apr 2012 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I didn't have this problem until I installed a different bluetooth stack on 
Win7_x64.

After a few hours looking for a solution, I realized the code had worked 
previously, so rather than learn any more about the windows I used the "system 
restore" function and it surprising worked after a couple reboots.

Why is it so hard just to make a dll on windows?
```

Original comment by `toddkauf...@gmail.com` on 26 Aug 2012 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
Awesome, snapshopshot 2.1.1 worked for me, using Windows 7 Home premium and 
NetBeans 7.2.1
```

Original comment by `mich...@prep-zone.com` on 11 Jan 2013 at 4:09

**Comment by GoogleCodeExporter** [comment]
```
snapshot 2.1.1 worked for me on windows 7 64x. I had to install WIDCOMM though.
```

Original comment by `mord...@gmail.com` on 23 Jan 2013 at 12:09

**Comment by GoogleCodeExporter** [comment]
```
I decided this problem in IDEA with Ant builder. You can find it there: 
Build-Generate Ant build.
Win 7 Home Basic 64x
bluecove snapshot 2.1.1
```

Original comment by `stra...@gmail.com` on 28 Mar 2013 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
I tried to use Bluecove with Windows 8 x64 and WIDCOMM. Since Bluecove doesn't 
support WIDCOMM 64-bit, I switched to a 32-bit JVM. Now it no longer says 
"Native Library 
bluecove_x64 not available" but instead gives the following error:
"WIDCOMM BluetoothStack not found"

I believe that starting with Windows Vista WIDCOMM integrates itself with the 
MS Bluetooth Stack and Bluecove thinks it's just the MS implementation. Is 
there any work around? I really needed to get RSSI information which is not 
possible while using the standard MS stack. In Linux it works fine with BlueZ 
but I'd like to support Windows as well (that's the whole point of making a 
Java application).

Any ideas?
```

Original comment by `petersai...@gmail.com` on 19 May 2013 at 10:16

**Comment by GoogleCodeExporter** [comment]
```
Yea the solution is the snapshot for W7 64 bits


```

Original comment by `dennysau...@gmail.com` on 5 Jun 2013 at 1:59

**Comment by GoogleCodeExporter** [comment]
```
Thank You Very Much Guys, i had same problem, now i installed SNAPSHOT and 
program is working
```

Original comment by `rahul.so...@gmail.com` on 12 Oct 2013 at 2:23

**Comment by GoogleCodeExporter** [comment]
```
I'm still experiencing this issue...where is the 64bit version of BlueCove? I 
can't find it
```

Original comment by `ilovemys...@gmail.com` on 4 Dec 2013 at 4:29

**Comment by GoogleCodeExporter** [comment]
```
谢谢楼主！
```

Original comment by `gbns2...@gmail.com` on 2 Mar 2014 at 1:50

**Comment by GoogleCodeExporter** [comment]
```
If people experience the following issue under Windows :
Native Library bluecove_x64 not available

It may be cause by your bluetooth driver. Make sure you update/install it 
properly. I kind of assumed that my driver was installed. However, few hours 
later I realized it wasn't.  

Sometimes we look way too far for a small problem....



```

Original comment by `stjean.g...@gmail.com` on 24 Mar 2014 at 3:45

**Comment by GoogleCodeExporter** [comment]
```
For me adding the JAR file specified in the following link did the trick -- 
http://snapshot.bluecove.org/distribution/download/2.1.1-SNAPSHOT/2.1.1-SNAPSHOT
.62/

```

Original comment by `kis...@tyfone.com` on 29 Apr 2014 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
Adding this dependency in my pom fixed the error "BlueCove native library 
version mismatch".

        <dependency>
            <groupId>org.ow2.chameleon.commons.bluecove</groupId>
            <artifactId>bluecove</artifactId>
            <version>2.1.1-63</version>
        </dependency>
```

Original comment by `pimhazeb...@gmail.com` on 25 May 2014 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
For the Project Remote Bluetooth Android 
https://github.com/luugiathuy/Remote-Bluetooth-Android I used the bluecove 
2.1.1. Snapshot, it executed without Errors, I was facing teh same error when I 
used the 2.1.0 varsion jars.
```

Original comment by `askera...@gmail.com` on 20 Jul 2014 at 11:36

**Comment by GoogleCodeExporter** [comment]
```
 I tried to use bluecove api in android, but it doesn't work. I added bluecove.jar(snapshot) and bluecove-gpl(snapshot version), i also added libbluecove.so at libs/armeabi. but it shows me an error that bluecove native library mismatch version. and often that while changing jar of different versions it shows me No JNI_OnLoad found in /data/data/skipping init 


```

Original comment by `aymen767...@gmail.com` on 6 May 2015 at 10:43

**Comment by GoogleCodeExporter** [comment]
```
i dont know why I have an error Exception Occured: 
javax.bluetooth.BluetoothStateException: BlueCove native library version 
mismatch
javax.bluetooth.BluetoothStateException: BlueCove native library version 
mismatch
    at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:454)
    at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:65) 

```

Original comment by `adel.fer...@gmail.com` on 6 May 2015 at 10:56
