### ISSUE TITLE
Problem with Toshiba Stack

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#114]
```
Hi, 

I have Toshiba notebook (Windows 7 x64) and use Toshiba Bluetooth stack. The 
bluetooth works fine.

I use Microlog for logging JavaME app to PC through Bluetooth. I can't run the 
bluetooth server:

java -cp 
bluecove-2.1.1-SNAPSHOT.jar;bluecove-gpl-2.1.1-SNAPSHOT.jar;microlog-server-blue
tooth-2.3.5.jar 

net.sf.microlog.server.btspp.gui.MicrologBluetoothServerUI Exception in thread 
"AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: 
com.intel.bluetooth.BluetoothStackToshiba.getLibraryVersion ()I at 
com.intel.bluetooth.BluetoothStackToshiba.getLibraryVersion(Native Method) at 
com.intel.bluetooth.BlueCoveImpl.setBluetoothStack(BlueCoveImpl.java:964) at 
com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:502) at 
com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69) at 
com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1044) at 
java.security.AccessController.doPrivileged(Native Method) at 
com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.java:1042) 
at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack(BlueCoveImpl.java:1035) 
at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:75) at 
javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:95) at 
net.sf.microlog.midp.bluetooth.server.BluetoothSerialServerThread.getDiscoverabl
eLocalDevice(BluetoothSerialServerThrea d.java:76) at 
net.sf.microlog.midp.bluetooth.server.BluetoothSerialServerThread.<init>(Bluetoo
thSerialServerThread.java:58) at 
net.sf.microlog.server.btspp.gui.MicrologBluetoothServerUI.<init>(MicrologBlueto
othServerUI.java:78) at 
net.sf.microlog.server.btspp.gui.MicrologBluetoothServerUI$1.run(MicrologBluetoo
thServerUI.java:61) at java.awt.event.InvocationEvent.dispatch(Unknown Source) 
at java.awt.EventQueue.dispatchEvent(Unknown Source) at 
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) at 
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) at 
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) at 
java.awt.EventDispatchThread.pumpEvents(Unknown Source) at 
java.awt.EventDispatchThread.pumpEvents(Unknown Source) at 
java.awt.EventDispatchThread.run(Unknown Source) 

I communicated with Microlog's developer. He recommended to ask BlueCove 
developers about this issue.

Further details can be found at:
https://sourceforge.net/projects/microlog/forums/forum/464718/topic/3754944/inde
x/page/1
```

Original issue reported on code.google.com by `alexey.a...@gmail.com` on 30 Jun 2010 at 8:35

**Comment by GoogleCodeExporter** [comment]
```
Additional information:
Bluetooth Stack for Windows by Toshiba v7.10.12(T)
```

Original comment by `alexey.a...@gmail.com` on 1 Jul 2010 at 6:12

**Comment by GoogleCodeExporter** [comment]
```
We don't have support for Toshiba Stack implemented in BlueCove.
```

Original comment by `skarzhev...@gmail.com` on 27 Jul 2010 at 1:41
