### ISSUE TITLE
Cant get it to work with IVT

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#13]
```
What steps will reproduce the problem?
1. Ive Put bluecove to my classpath
2. everything is ok with stack - my drivers match those from site's screenshots
3. i use that code for init of BT Server : http://phpfi.com/239055

i get folowing Exception :
BlueCove version 1.2.3
java.io.IOException: Failed to create socket
    at com.intel.bluetooth.BluetoothPeer.socket(Native Method)
    at
com.intel.bluetooth.BluetoothStreamConnectionNotifier.<init>(BluetoothStreamConn
ectionNotifier.java:54)
    at
com.intel.bluetooth.MicroeditionConnector.openImpl(MicroeditionConnector.java:13
5)
    at
com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.java:75)
    at javax.microedition.io.Connector.open(Connector.java:79)
    at ServerThread.run(ServerThread.java:35)

When calling : notifier = (StreamConnectionNotifier)Connector.open(url);

PLEASE help

i know its not support forum but it seems that this is bluecove problem not
my code prob.. :/
```

Original issue reported on code.google.com by `yacho1...@gmail.com` on 3 Jun 2007 at 2:26

**Comment by GoogleCodeExporter** [comment]
```
The version 2.0 is still work in progress. In published SNAPSHOT
version you can't YET open the BT Server when using IVT
stack.

Only Client is implemented: e.g. You can find devices, do service
search and connect to other BT servers.

Server in WIDCOMM is already in SVN is published.

Server in IVT stack would be done later or if you are interested you
add code yourself and send me the patch.

Watch Changelog http://code.google.com/p/bluecove/wiki/Changelog when
this work would be finished. 
```

Original comment by `skarzhev...@gmail.com` on 4 Jun 2007 at 6:22
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
IVT stack server implemented
```

Original comment by `skarzhev...@gmail.com` on 15 Jun 2007 at 6:54
- Changed state: **Fixed**
