### ISSUE TITLE
Make bluecove work with bluesoleil stack

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#137]
```
What steps will reproduce the problem?
1. The current bluetooth stack is Bluesoleil
2. I try to get the LocalDevice in order to start a new serveur :  LocalDevice 
localDevice = LocalDevice.getLocalDevice();
3. It say's that the BluetoothStack is not detected

Expected output : 
I get the local Device in order to start a new Serveur : 


LocalDevice localDevice = LocalDevice.getLocalDevice();
System.out.println("Address: "+localDevice.getBluetoothAddress());
System.out.println("Name: "+localDevice.getFriendlyName());
Serveur sampleSPPServer = new Serveur();
sampleSPPServer.startServer();

With : 

public void startServer() throws IOException {
uuid = new UUID("1101",true);
connectionString = "btspp://localhost:" + uuid + ";name= Server";
System.out.println("\nMise en place serveur");
streamConnNotifier = (StreamConnectionNotifier) 
Connector.open(connectionString);
System.out.println("\nServer Started. Waiting for clients to connect...");
connection = streamConnNotifier.acceptAndOpen();
...}



Instead : I get this error : 

Exception in thread "main" javax.bluetooth.BluetoothStateException: 
BluetoothStack not detected
    at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:496)
    at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)
    at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1044)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.java:1042)
    at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack(BlueCoveImpl.java:1035)
    at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:75)
    at javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:95)
    at Serveur.main(Serveur.java:116)



What BlueCove version are you using (include build number for SNAPSHOT)?

bluecove-2.1.1-SNAPSHOT

On what operating system and jvm? Is this 64-bit or 32-bit OS and jvm?

Windows 64 bit


Please provide any additional information below.

I want to implement on my computer a bluetooth serveur in order to connect a 
smartphone wich behave as a client (using the android Bluetooth library), with 
a possibility to have multiples smartphones connected, in order to send 
messages between the smartphones and the computer.
I just don't know how to change the default stack on bluecove in order to make 
it work with bluesoleil (I don't know exacly what I should do or what code I 
should write).

I hope I have explain clearly my problem

Thanks for your help:)

Emile
```

Original issue reported on code.google.com by `emile.qu...@gmail.com` on 18 Feb 2013 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
i have the same problem :(
```

Original comment by `mehdee.m...@gmail.com` on 9 Aug 2014 at 2:10
