### ISSUE TITLE
rfcomm connection disconnected after 37 sec

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#24]
```
hi all!
i'm using bluecove 2.0.0 with bluesoleil 1.6.1.4 and bluesoleil 2.6.0.8 on 
windows XP for pc to pc client server communication using  rfcomm .

i'm able to communicate once between the client and server but by the time 
the server has received the message and is supposed to open outputstream 
to write to the client,the client has disconnected (it connects for only 
about 37 sec) without giving me a timeout exception.(am using 
connector.open(url,2,true)).

so i get :
java.io.IOException: Failed to write to closed connection
        at com.intel.bluetooth.BluetoothStackBlueSoleil.connectionRfWrite
(Native
 Method)
        at com.intel.bluetooth.BluetoothOutputStream.write
(BluetoothOutputStream
.java:81)
        at java.io.DataOutputStream.write(DataOutputStream.java:90)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:80)
        at EchoServer.main(EchoServer.java:179)
closing input stream at server
closing output stream at server
BlueCove stack shutdown completed
Press any key to continue...

i want to know if this is a limitation of bluesoleil or is there any way 
to reconnect again?how can i increase the timeout limit?

needs get this working by next week.suggestions plz??




```

Original issue reported on code.google.com by `killeran...@gmail.com` on 4 Jan 2008 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
0) Are you sure your client is not closing connection? I have not seen such a 
problem!
1) First use the latest version of BlueCove 2.0.1 or 2.0.2-SNAPSHOT
2) Make sure you have a proper licenced dongle from bluesoleil 
3) Try to make connection to other than bluesoleil device do you still have the 
same
problem? 
```

Original comment by `skarzhev...@gmail.com` on 4 Jan 2008 at 4:08

**Comment by GoogleCodeExporter** [comment]
```
0) yes,i'm sure my client is not closing connection because i get the exception 
before the client has closed its streamconnection object(as i'm printing 
connnection 
closed statement after i call it,which never gets displayed).

1) i'll try to download the latest bluecove version (it 'll take me a lot of 
trouble 
to download  it :()

2) i hope i have a licensed dongle,i just went and bought it from the 
market.they 
were supposed to sell me the licensed one!!!!

3)i'll try this.maybe the problem is because i'm using devices which use 
different 
versions of bluesoleil(1.6.1.4 and 2.6.0.8,some differnece!!) but it's driving 
me 
crazy!!

thanks for your response.feel a lot better now!:)

```

Original comment by `killeran...@gmail.com` on 4 Jan 2008 at 4:41

**Comment by GoogleCodeExporter** [comment]
```
Just tested my test application with
bluesoleil 1.6.1.4 and Dongle BlueSoleil BS001 connected to another computer 
with
Broadcom Bluetooth stack. All works fine!
Connection was open for 4 minuts. No problem
```

Original comment by `skarzhev...@gmail.com` on 4 Jan 2008 at 6:04
- Added labels: **OpSys-Windows**, **Priority-Low**, **Type-Other**
- Removed labels: **Priority-Medium**, **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
thanks for checking it out. i ran your test application bluecove test on my pcs 
but 
it didn't run on my bluesoleil version 2. so i checked it out with 2 version 
1.6.1.4  devices. it worked fine but i'm still having the same problem with my 
code.maybe there is some error in my program butit's strange that i'm able to 
communicate once and not again.it's not fair!!
this is what i'm getting at the client:

com.intel.bluetooth.BluetoothRFCommClientConnection@157f0dc
output stream opened here.....
client has written on the output stream...
server conn objcom.intel.bluetooth.BluetoothRFCommClientConnection@157f0dc
ouput stream closed
java.io.IOException
        at com.intel.bluetooth.BluetoothRFCommConnection.openInputStream(Bluetoo
thRFCommConnection.java:90)
        at com.intel.bluetooth.BluetoothRFCommConnection.openDataInputStream(Blu
etoothRFCommConnection.java:105)
        at EchoClient.serviceSearchCompleted(EchoClient.java:147)
        at com.intel.bluetooth.SearchServicesThread.run(SearchServicesThread.jav
a:115)
BlueCove stack shutdown completed
Press any key to continue...

```

Original comment by `killeran...@gmail.com` on 7 Jan 2008 at 11:45

**Comment by GoogleCodeExporter** [comment]
```
also,how do i verify if i have a licensed device or not.
```

Original comment by `killeran...@gmail.com` on 7 Jan 2008 at 11:45

**Comment by GoogleCodeExporter** [comment]
```
If you install bluesoleil drivers and it does not say evaluation license then 
you
probably fine. Also I have seen many counterfeited BT dongles packaged with
bluesoleil software.
If you have problem running my test application then something seriously wrong 
with
your system. Since I have no support from bluesoleil I can't help you here. Try 
to
figure out on your own. Make shure connection are closed properly and if you 
stuck
reboot Windows and try again.
```

Original comment by `skarzhev...@gmail.com` on 7 Jan 2008 at 3:44
- Changed state: **Invalid**
