### ISSUE TITLE
ClassNotFoundException on Mac OSX + mpowerplayer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#38]
```
What steps will reproduce the problem?
After EVENT_DISCOVER_SERVICE_COMPLETED just try to connect on any service
on device.

What is the expected output? What do you see instead?
Instead of EVENT_CLIENT_CONNECTED event I'm getting the following exception:

java.lang.ClassNotFoundException: de.avetana.bluetooth.connection.Connector


What BlueCove version are you using (include build number for SNAPSHOT)? On
what operating system and jvm? Is this 64-bit or 32-bit OS and jvm?

Bluecove-2.0.3-20080609.054350-87 already tested with bluecove-2.0.2.

I'm on iMac Intel, running Leopard 10.5.2.

java version "1.5.0_13"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_13-b05-237)
Java HotSpot(TM) Client VM (build 1.5.0_13-119, mixed mode, sharing)

I'm using the Mpowerplayer SDK 2.0 build 1185

Please provide any additional information below.

The full trace:

java.lang.ClassNotFoundException: de.avetana.bluetooth.connection.Connector

java.lang.RuntimeException
    at processing.bluetooth.Bluetooth.start(Unknown Source)
    at tictactoe.keyPressed(tictactoe.java:211)
    at processing.core.PMIDlet.keyPressed(Unknown Source)
    at processing.core.PMIDlet.dequeueEvents(Unknown Source)
    at processing.core.PMIDlet.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:613)



```

Original issue reported on code.google.com by `lup...@gmail.com` on 16 Jun 2008 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
I see that your application is looking for avetana. Use avetana support to get 
it
working. avetana is alternative to BlueCove commercial JSR-82 implementation.

mpowerplayer is closed source and not supported By BlueCove team. Use 
mpowerplayer
support forums.  In general BlueCove should work with mpowerplayer.

For J2ME applications running in J2SE use open source MicroEmulator
http://www.microemu.org/



```

Original comment by `skarzhev...@gmail.com` on 16 Jun 2008 at 10:14
- Changed state: **WontFix**
