### ISSUE TITLE
NotSupportedIOException on BlueSoleil

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#43]
```
What steps will reproduce the problem?

when connecting l2cap connection to write on a BlueSoleil drive,
NotSupportedIOException will occur

L2CAPConnection controlCon= (L2CAPConnection)Connector.open(
"btl2cap://" + device.getBluetoothAddress() +
":11;authenticate=false;encrypt=false;master=false", Connector.WRITE);


What is the expected output? What do you see instead?

the exception is as follows,
Exception: com.intel.bluetooth.NotSupportedIOException: Not Supported on
bluesoleil
    at
com.intel.bluetooth.BluetoothStackBlueSoleil.l2OpenClientConnection(BluetoothSta
ckBlueSoleil.java:326)
    at
com.intel.bluetooth.BluetoothL2CAPClientConnection.<init>(BluetoothL2CAPClientCo
nnection.java:32)
    at
com.intel.bluetooth.MicroeditionConnector.openImpl(MicroeditionConnector.java:35
4)
    at
com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.java:149)
    at
com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.java:446)
    at javax.microedition.io.Connector.open(Connector.java:93)
    at device.Wiimote.connect(Wiimote.java:135)
    ...


What BlueCove version are you using (include build number for SNAPSHOT)? On
what operating system and jvm? Is this 64-bit or 32-bit OS and jvm?

BlueCove 2.0.2
BlueSoleil 3.2.2.8 Release 070421
Stack 06.03.29.20061212
Windows XP SP2
JDK 1.6.0
32-bit OS and jvm


Please provide any additional information below.

Bluetooth device can be found correctly, and device.getBluetoothAddress()
works as well. But I don't know why it couldn't get connected. It doesn't
matter if it's Connector.WRITE or Connector.REA or delete
"authenticate=false;encrypt=false;master=false".
I tried BlueCove 2.0.1 and 2.0.0 as well but neither will work.


```

Original issue reported on code.google.com by `james....@gmail.com` on 24 Jul 2008 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
l2cap Not Supported on bluesoleil. This is bluesoleil API limitation
See http://code.google.com/p/bluecove/wiki/stacks

```

Original comment by `skarzhev...@gmail.com` on 28 Jul 2008 at 2:12
- Changed state: **WontFix**
- Added labels: **OpSys-Windows**
