### ISSUE TITLE
Mysaifu 1.6 BlueCove 2.0.3 on HP Ipaq 24xx unable to load proper BT stack during initial dicovery

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#56]
```


Goodmorning,





I am trying desperately to run Mysaifu on a an a IPaq 2790 HP PDA with 
ARM920T PXA27x with 56 Mb using Windows Mobile 5.1.1702 Build 14366.1.0.1 
and I get the following stack below.

The \Application Data\Volatile\Mysaifu JVM\bluecove_IPAQ2490_0
\bluecove_ce.dll file exits although \Application Data\Volatile\Mysaifu 
JVM\bluecove_IPAQ2490_0\intelbth_ce.dll which it should

use based on the System property bluecove.stack which is set to widcomm in 
the VM Propertes TAB of the JVM  and which is also mentioned in the below 
line



23:21:53.337 detector stack widcomm



it still tries to load the existsing 



       \Application Data\Volatile\Mysaifu JVM\bluecove_IPAQ2490_0
\bluecove_ce.dll



although as mentioned before it should load 



       \Application Data\Volatile\Mysaifu JVM\bluecove_IPAQ2490_0
\intelbth_ce.dll



note that both these files do exists!



I also tried to copy bluecove_ce.dll and intelbth_ce.dll into the mysaife 
jre bin  and My Documents directory, both without any luck.







I would like to try version 2.1 because it seems that this problem is 
solved in 2.1 but don´t know how to fetch-download it from google code or 
any other place. Can 

you tell me where to find it as a complete jar just as 2.0.3?







Any help is greatly appriciated.





André



ps. I just started using this JVM, put I am interested also if Swing or 
just AWT is supported in 2.03 and or future 2.1 versions. Which demo can I 
run to see

almost all GUI supoorted features or is there an exact secification with 
is currently supoorted in 2.0.3?



pps on my IPaq I use Bt for Windows CE BT/PPC version 1.7.1. build 1424








°°°°°°°°°°°°°°°°°°°°°°°°°°°°



The following file is a trace when trying to run Dicovery







23:21:30.963 Stating app

23:21:35.442 Stated app

23:21:36.626 OS:Windows CE|5.1|arm

23:21:36.719 Java:Mysaifu 1.6

23:21:41.510 BlueCove Debug enabled

23:21:41.540 Java 1.4+ detected: 1.6; Mysaifu JVM; Mysaifu

com.intel.bluetooth.UtilsJavaSE.getLocation(UtilsJavaSE.java:121)

net.sf.bluecove.se.BlueCoveLoggerAppender.changeDebug
(BlueCoveLoggerAppender.java:-1)

23:21:53.337 detector stack widcomm

com.intel.bluetooth.BlueCoveImpl.createDetectorOnWindows
(BlueCoveImpl.java:864)

23:21:54.133 Use stack ClassLoader

com.intel.bluetooth.NativeLibLoader.loadAsSystemResource
(NativeLibLoader.java:271)

23:21:56.979 error Can't load library file java.lang.UnsatisfiedLinkError: 
Could not load library \Application Data\Volatile\Mysaifu 
JVM\bluecove_IPAQ2490_0\bluecove_ce.dll

com.intel.bluetooth.NativeLibLoader.loadAsSystemResource
(NativeLibLoader.java:313)

java.lang.UnsatisfiedLinkError: Could not load library \Application 
Data\Volatile\Mysaifu JVM\bluecove_IPAQ2490_0\bluecove_ce.dll

at java.lang.Runtime.load(Runtime.java:682)

at java.lang.System.load(System.java:643)

at com.intel.bluetooth.NativeLibLoader.loadAsSystemResource
(NativeLibLoader.java:310)

at com.intel.bluetooth.NativeLibLoader.isAvailable
(NativeLibLoader.java:197)

at com.intel.bluetooth.BlueCoveImpl.isNativeLibrariesAvailable
(BlueCoveImpl.java:407)

at com.intel.bluetooth.BlueCoveImpl.createDetectorOnWindows
(BlueCoveImpl.java:868)

at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:442)

at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)

at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1025)

at java.security.AccessController.doPrivileged(AccessController.java:195)

at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged
(BlueCoveImpl.java:1023)

at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack
(BlueCoveImpl.java:1016)

at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:77)

at javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:97)

at net.sf.bluecove.TestResponderCommon.initLocalDeviceConfig
(TestResponderCommon.java:65) at 
net.sf.bluecove.TestResponderCommon.startLocalDevice
(TestResponderCommon.java:60)

at net.sf.bluecove.TestResponderClient.<init>(TestResponderClient.java:586)

at net.sf.bluecove.Switcher.createClient(Switcher.java:292)

at net.sf.bluecove.Switcher.createClient(Switcher.java:285)

at net.sf.bluecove.Switcher.startDiscovery(Switcher.java:349)

at net.sf.bluecove.awt.Main$7.actionPerformed(Main.java:175)

at java.awt.MenuItem.processActionEvent(MenuItem.java:576)

at java.awt.MenuItem.processEvent(MenuItem.java:560)

at java.awt.MenuItem.dispatchEventImpl(MenuItem.java:542)

at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:347)

at java.awt.EventQueue.dispatchEvent(EventQueue.java:629)

at java.awt.EventDispatchThread.run(EventDispatchThread.java)

at java.lang.VMThread.run(VMThread.java:120)

23:21:57.589 error Library bluecove_ce not loaded 
java.lang.UnsatisfiedLinkError: Native library `bluecove_ce' not found (as 
file `bluecove_ce') in gnu.classpath.boot.library.path and 
java.library.path

com.intel.bluetooth.NativeLibLoader.tryload(NativeLibLoader.java:220)

java.lang.UnsatisfiedLinkError: Native library `bluecove_ce' not found (as 
file `bluecove_ce') in gnu.classpath.boot.library.path and 
java.library.path

at java.lang.Runtime.loadLibrary(Runtime.java:763)

at java.lang.System.loadLibrary(System.java:662)

at com.intel.bluetooth.NativeLibLoader.tryload(NativeLibLoader.java:217)

at com.intel.bluetooth.NativeLibLoader.isAvailable
(NativeLibLoader.java:201)

at com.intel.bluetooth.BlueCoveImpl.isNativeLibrariesAvailable
(BlueCoveImpl.java:407)

at com.intel.bluetooth.BlueCoveImpl.createDetectorOnWindows
(BlueCoveImpl.java:868)

at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:442)

at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)

at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1025)

at java.security.AccessController.doPrivileged(AccessController.java:195)

at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged
(BlueCoveImpl.java:1023)

at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack
(BlueCoveImpl.java:1016)

at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:77)

at javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:97)

at net.sf.bluecove.TestResponderCommon.initLocalDeviceConfig
(TestResponderCommon.java:65)

at net.sf.bluecove.TestResponderCommon.startLocalDevice
(TestResponderCommon.java:60)

at net.sf.bluecove.TestResponderClient.<init>
(TestResponderClient.java:586) at net.sf.bluecove.Switcher.createClient
(Switcher.java:292) at net.sf.bluecove.Switcher.createClient
(Switcher.java:285) at net.sf.bluecove.Switcher.startDiscovery
(Switcher.java:349)

at net.sf.bluecove.awt.Main$7.actionPerformed(Main.java:175)

at java.awt.MenuItem.processActionEvent(MenuItem.java:576)

at java.awt.MenuItem.processEvent(MenuItem.java:560)

at java.awt.MenuItem.dispatchEventImpl(MenuItem.java:542)

at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:347)

at java.awt.EventQueue.dispatchEvent(EventQueue.java:629)

at java.awt.EventDispatchThread.run(EventDispatchThread.java)

at java.lang.VMThread.run(VMThread.java:120)

Native Library bluecove_ce not available

23:21:57.167 java.library.path \Program Files\Mysaifu JVM\jre\bin

com.intel.bluetooth.NativeLibLoader.isAvailable(NativeLibLoader.java:209)

23:21:58.616 Use stack ClassLoader

com.intel.bluetooth.NativeLibLoader.loadAsSystemResource
(NativeLibLoader.java:271)

23:21:58.065 Library loaded from \Application Data\Volatile\Mysaifu 
JVM\bluecove_IPAQ2490_0\intelbth_ce.dll

com.intel.bluetooth.NativeLibLoader.loadAsSystemResource
(NativeLibLoader.java:311)

23:21:58.204 nativeDebugCallback ON

common.cpp:60

23:21:58.248 BluetoothStack selected widcomm

com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:482)

23:21:58.408 error start error javax.bluetooth.BluetoothStateException: 
BlueCove library bluecove not available

javax.bluetooth.BluetoothStateException: BlueCove library bluecove not 
available

at com.intel.bluetooth.BlueCoveImpl.loadNativeLibraries
(BlueCoveImpl.java:384)

at com.intel.bluetooth.BlueCoveImpl.setBluetoothStack
(BlueCoveImpl.java:942)

at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:485) at 
com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)

at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1025)

at java.security.AccessController.doPrivileged(AccessController.java:195)

at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged
(BlueCoveImpl.java:1023)

at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack
(BlueCoveImpl.java:1016)

at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:77)

at javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:97)

at net.sf.bluecove.TestResponderCommon.initLocalDeviceConfig
(TestResponderCommon.java:65)

at net.sf.bluecove.TestResponderCommon.startLocalDevice
(TestResponderCommon.java:60)

at net.sf.bluecove.TestResponderClient.<init>(TestResponderClient.java:586)

at net.sf.bluecove.Switcher.createClient(Switcher.java:292)

at net.sf.bluecove.Switcher.createClient(Switcher.java:285)

at net.sf.bluecove.Switcher.startDiscovery(Switcher.java:349)

at net.sf.bluecove.awt.Main$7.actionPerformed(Main.java:175)

at java.awt.MenuItem.processActionEvent(MenuItem.java:576)

at java.awt.MenuItem.processEvent(MenuItem.java:560)

at java.awt.MenuItem.dispatchEventImpl(MenuItem.java:542)

at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:347)

at java.awt.EventQueue.dispatchEvent(EventQueue.java:629)

at java.awt.EventDispatchThread.run(EventDispatchThread.java)

at java.lang.VMThread.run(VMThread.java:120)

javax.bluetooth.BluetoothStateException: BlueCove library bluecove not 
available

at com.intel.bluetooth.BlueCoveImpl.loadNativeLibraries
(BlueCoveImpl.java:384)

at com.intel.bluetooth.BlueCoveImpl.setBluetoothStack
(BlueCoveImpl.java:942)

at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:485) at 
com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)

at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1025)

at java.security.AccessController.doPrivileged(AccessController.java:195)

at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged
(BlueCoveImpl.java:1023)

at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack
(BlueCoveImpl.java:1016)

at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:77)

at javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:97)

at net.sf.bluecove.TestResponderCommon.initLocalDeviceConfig
(TestResponderCommon.java:65)

at net.sf.bluecove.TestResponderCommon.startLocalDevice
(TestResponderCommon.java:60)

at net.sf.bluecove.TestResponderClient.<init>(TestResponderClient.java:586)

at net.sf.bluecove.Switcher.createClient(Switcher.java:292)

at net.sf.bluecove.Switcher.createClient(Switcher.java:285)

at net.sf.bluecove.Switcher.startDiscovery(Switcher.java:349)

at net.sf.bluecove.awt.Main$7.actionPerformed(Main.java:175)

at java.awt.MenuItem.processActionEvent(MenuItem.java:576)

at java.awt.MenuItem.processEvent(MenuItem.java:560)

at java.awt.MenuItem.dispatchEventImpl(MenuItem.java:542)

at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:347)

at java.awt.EventQueue.dispatchEvent(EventQueue.java:629)

at java.awt.EventDispatchThread.run(EventDispatchThread.java)

at java.lang.VMThread.run(VMThread.java:120)

23:21:59.349 detector stack widcomm

com.intel.bluetooth.BlueCoveImpl.createDetectorOnWindows
(BlueCoveImpl.java:864)

23:22:00.471 BluetoothStack selected widcomm

com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:482)

Exception during event dispatch:

java.lang.RuntimeException: BlueCove library bluecove not available

at javax.bluetooth.LocalDevice.getProperty(LocalDevice.java:321)

at net.sf.bluecove.se.UIHelper.getMainWindowTitle(UIHelper.java:48)

at net.sf.bluecove.awt.Main.updateTitle(Main.java:493)

at net.sf.bluecove.awt.Main.access$100(Main.java:69)

at net.sf.bluecove.awt.Main$7.actionPerformed(Main.java:176)

at java.awt.MenuItem.processActionEvent(MenuItem.java:576)

at java.awt.MenuItem.processEvent(MenuItem.java:560)

at java.awt.MenuItem.dispatchEventImpl(MenuItem.java:542)

at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:347) at 
java.awt.EventQueue.dispatchEvent(EventQueue.java:629)

at java.awt.EventDispatchThread.run(EventDispatchThread.java) at 
java.lang.VMThread.run(VMThread.java:120)

Caused by: javax.bluetooth.BluetoothStateException: BlueCove library 
bluecove not available

at com.intel.bluetooth.BlueCoveImpl.loadNativeLibraries
(BlueCoveImpl.java:384)

at com.intel.bluetooth.BlueCoveImpl.setBluetoothStack
(BlueCoveImpl.java:942)

at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:485)

at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)

at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1025)

at java.security.AccessController.doPrivileged(AccessController.java:195)

at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged
(BlueCoveImpl.java:1023)

at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack
(BlueCoveImpl.java:1016)

at javax.bluetooth.LocalDevice.getProperty(LocalDevice.java:308)

...11 more

```

Original issue reported on code.google.com by `kou...@telfort.nl` on 26 Nov 2008 at 2:07

**Comment by GoogleCodeExporter** [comment]
```
Get the last jar bluecove-2.1.0-20081122.060125-15.jar from build server.
http://www.pyx4me.com/maven2-snapshot/net/sf/bluecove/bluecove/2.1.0-SNAPSHOT/

The main site has a link: "Nightly BlueCove Build" http://snapshot.bluecove.org/

The Nightly build site has a left menu "Download" ->  "Snapshot"

And please use "Attach a file" when uploading stack traces!
```

Original comment by `skarzhev...@gmail.com` on 26 Nov 2008 at 2:44

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
The answer is simple:
 I don't have IPaq so I can't test the BlueCove build on this hardware.
 So I can't say it runs or not. 
 If you would be so kind to join the project and report every now and then the status
of IPaq support then it would be helpful.
  Also the version 2.0.1 and 2.0.2 should be identical to 2.1 from Windows CE point
of view. Simple 2.0.3 had glitch in build, I'm changing this...

Vlad
```

Original comment by `skarzhev...@gmail.com` on 26 Nov 2008 at 1:56

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
The project is hosted on sf.net and google code. So you need sf.net to Edit WIKI
pages on sf.net and google account to commit to SVN and edit WIKI pages on 
google site.

All talking should be done in Groups/mailing lists.

The build system is maintained on build server by Pyx Software Services, Only 
Me and
Michael has access to the build system https://pyx4j.com and this is not 
negotiable
now since this is private system.

For you I can suggest to use http://bluecove.wiki.sourceforge.net/ 
The google code does not give a different privileges to developers and testers 
now.
So for all the testing docs the sf.net should ne used.

```

Original comment by `skarzhev...@gmail.com` on 27 Nov 2008 at 2:19

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
You can always remove the dll from the jar and place it them in folder 
accessible by
JVM all should work if the stack is working.

 So what you should do is:
1. Identify the stack your system has.
     Use intelbth_ce.dll or bluecove_ce.dll
     -Dbluecove.native.resource=false
   -Dbluecove.stack=widcomm
      -Dbluecove.stack=winsock

   (I think that Windows Mobile 5  has MS stack NOT widcomm)

2. Try different JVM, Different JVM version  I used Mysaifu JVM Version 0.3.4 
on my
Dell AXIM X30.

3. Try compiling dlls using different MS SDK.

I would probably have a budget and time to buy Mobile 5 device next year. And 
see for
myself, until then ... I only know what have been reported in mailing list by 
users.
```

Original comment by `skarzhev...@gmail.com` on 27 Nov 2008 at 4:11

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
1)  Motorola MPx220, Windows Mobile 2003 Phone Edition
      Microsoft Bluetooth stack
      Used Mysaifu JVM Version 0.3.4

2)  Dell AXIM X30, Windows Mobile 2003 SE (WinCE 4.21)
      Broadcom Bluetooth stack BT-PPC 1.5.0.4300
      Used Mysaifu JVM Version 0.3.4 and 0.3.6

Tested the BlueCove 2.0.2, In version 2.0.3 I made an error during final build  
so it
will not work on ms stack.
```

Original comment by `skarzhev...@gmail.com` on 27 Nov 2008 at 7:05

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
You can't take BlueCove DLL from one version and use it with classes from jar 
from
another build.
e.g. 2.0.3 dlls will not work for 2.1 classes.
Every dll has a version inside just look Using Windows Explorer. Also each jar 
has
manifest. That contains the version information.

The 2000277  is the dlls from 2.0.2  build the classes you have are 2000399 
2.0.3
This was specialy done becuase we are changing signatures of some functions 
from time
to time and wnat to avoid the Runtime errors.
```

Original comment by `skarzhev...@gmail.com` on 27 Nov 2008 at 11:18

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
PLEASE Please, Please, Please, Please STOP this! Use E-mail.
The bug is not a place for general discussions.

I can't help you to find the dlls or jars on your computer. Just see what is in 
the
path or do a general search for the dll.  You know the name.

If Does not help reinstall windows.
Then start from scratch, Recording in some text file what you are doing and what
version of which files you are placing in what location.

When you copy the dll to Windows XP in explorer you can see the dll version.
Also If you open the jar using Winrar or Winzip you can see the context of 
manifest file.

!!!!!!! DO NOT REPLY TO THIS BUG REPORT ANYMORE !!!!!!!!
```

Original comment by `skarzhev...@gmail.com` on 27 Nov 2008 at 11:42

Attachments:
- [dll-version-info.png](https://storage.googleapis.com/google-code-attachments/bluecove/issue-56/comment-16/dll-version-info.png)

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi André
  I would reply to your e-mail but I don't know it so I will repeat myslef!

  As I told Use: skarzhevskyy@gmail.com or group bluecove-users@googlegroups.com to
ask the questions.

  I can't teach you how to use Windows CE. And I see this what you want from the
thread! The HOWTO use Windows was never a topic for BlueCove project support!
 If you want to discuss the best way to work with Windows CE you are welcome. But not
here! The benefit of using googlegroups is that they are search able and it 
would be
easy for others to find the problem and solution.  
 Also in googlegroups somebody else will help you with advice.
 In the issues only I will answer. And so on.....

 Yes I made the fatal mistake by not testing the version 2.0.3 build.  But previous
version 2.0.2 and next version 2.1 are all OK and tested by users. And this bug 
is
all about this!  And I can't close the issue because the current Release 2.0.3 
has
this build problem. And only once next version is released the bug would be 
closed.

 So André I value your persistence but.

!!!!!!! DO NOT REPLY TO THIS BUG !!!!!!!!
!!!!!!! De ne pas répondre       !!!!!!!!!
!!!!!!! НЕ ОТВЕЧАЙ БОЛЬШЕ        !!!!!!!!!
```

Original comment by `skarzhev...@gmail.com` on 28 Nov 2008 at 12:16
- Changed state: **Accepted**
- Added labels: **OpSys-WinCE**

**Comment by GoogleCodeExporter** [comment]
Original comment by `skarzhev...@gmail.com` on 22 Dec 2008 at 8:22
- Changed state: **Invalid**
