### ISSUE TITLE
BlueZ v4 Unable to retrieve the local discovery mode.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#59]
```
LocalDevice.setDiscoverable() produce this error

java.lang.RuntimeException: Unable to retrieve the local discovery mode.
BluetoothStackBlueZ.nativeGetLocalDeviceDiscoverable
com.intel.bluetooth.BluetoothStackBlueZ.getLocalDeviceDiscoverable(BluetoothStac
kBlueZ.java:272)

Even when I run as root!

Tested on Fedora 10 under VMWare

This is a show stopper for running TCK on Linux
```

Original issue reported on code.google.com by `skarzhev...@gmail.com` on 10 Dec 2008 at 4:21

**Comment by GoogleCodeExporter** [comment]
```
LocalDevice.setDiscoverable (with root) and LocalDevice.getDiscoverable() works 
very
well for me on Ubuntu 8.10 64-bits.

I'll try to get fedora 10 and make test on it..
```

Original comment by `minasho...@gmail.com` on 10 Dec 2008 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
On Fedora 9 in real Box all works fine.
So Looks like this a the problem while running in VMWare
```

Original comment by `skarzhev...@gmail.com` on 13 Feb 2009 at 8:10
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem on Mandriva cooker (NOT using VMWare), root user.

bluez-4.33
kernel 2.6.27.19

Works fine with bluez 3
```

Original comment by `p.filip...@gmail.com` on 16 Apr 2009 at 7:01

**Comment by GoogleCodeExporter** [comment]
```
I am having this problem with Ubuntu 9.04
```

Original comment by `fabi...@gmail.com` on 25 Apr 2009 at 5:57

**Comment by GoogleCodeExporter** [comment]
```
I'm also having this problem, even running the application as root, and have no 
idea
how to circumvent it.

I'm on Gentoo, using bluez 4.39 and bluecove 2.1.0 on a kernel 2.6.27.

Any help would be much appreciated.

- Joao
```

Original comment by `jecl...@gmail.com` on 17 May 2009 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
Hi,

i am student and write now the program code for bluetooth application
to transfer the files between PC (server) and mobile telephone
(client). The files could be transmitted between server (Windows PC)
and mobile telephone and now I want to use linux system as server. But
the program under linux worked only at the first time, later works
not.
I have imported   bluecove-2.1.1-SNAPSHOT.jar      bluecove-gpl-2.1.1-
SNAPSHOT.jar   bluecove-bluez-2.1.1-SNAPSHOT.jar  as library in
eclipse and started as superuser (/root). My system is: openSUSE 11.1

The error code ist:

Exception in thread "Thread-1"
java.lang.RuntimeException: Unable to retrieve the local discovery
mode.
at
com.intel.bluetooth.BluetoothStackBlueZ.nativeGetLocalDeviceDiscoverable
(Native Method)
at com.intel.bluetooth.BluetoothStackBlueZ.getLocalDeviceDiscoverable
(BluetoothStackBlueZ.java:289)
at com.intel.bluetooth.BluetoothStackBlueZ.setLocalDeviceDiscoverable
(BluetoothStackBlueZ.java:303)
at javax.bluetooth.LocalDevice.setDiscoverable(LocalDevice.java:206)
at de.scheller.demo.PCServerOBEX.run(PCServerOBEX.java:319)
at java.lang.Thread.run(Thread.java:636)

I will post the program code (jar-file) in this group and hope that
somebody can test it for me and give me the information, under which
conditions the program can work. You can use this progam to
communicate with the mobile telephone's bluetooth. Under Windows the
program works definitiv and worked only once under linux. Thank you
for your help and sorry for this poor english. 
```

Original comment by `y....@scheller.de` on 19 May 2009 at 11:48

Attachments:
- [BluetoothPCImageReceiver.jar](https://storage.googleapis.com/google-code-attachments/bluecove/issue-59/comment-6/BluetoothPCImageReceiver.jar)
- [BluetoothPCImageReceiver.txt](https://storage.googleapis.com/google-code-attachments/bluecove/issue-59/comment-6/BluetoothPCImageReceiver.txt)

**Comment by GoogleCodeExporter** [comment]
```
I have the same issue as above with ubuntu Jaunty. Can you please tell me how 
the
problem was solved.
```

Original comment by `supd...@gmail.com` on 13 Jun 2009 at 10:50

**Comment by GoogleCodeExporter** [comment]
```
I am able to reproduce this issue with root on ubuntu 9.04
```

Original comment by `minasho...@gmail.com` on 13 Jun 2009 at 2:08
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Please all who have this issue, download latest code from repository, build, 
and test
again and give your feedback if it works.
```

Original comment by `minasho...@gmail.com` on 13 Jun 2009 at 2:27
- Changed state: **Fixed-SNAPSHOT**

**Comment by GoogleCodeExporter** [comment]
```
This fixed is applied to 2.1.1-SNAPSHOT.48 or later, Should be created on June 
14
```

Original comment by `skarzhev...@gmail.com` on 13 Jun 2009 at 3:33

**Comment by GoogleCodeExporter** [comment]
```
The snapshot site seems to be down can you please post a link to a place where 
I can
get it. Thanks guys for the quick reply :) 
```

Original comment by `supd...@gmail.com` on 13 Jun 2009 at 5:56

**Comment by GoogleCodeExporter** [comment]
```
As I told SNAPSHOT would be created only tonight on June 14,

SNAPSHOT  site is back again I moved the server already!

Also Mina keep in mind that server is building libraries only at night and the 
night in 
Toronto, Canada (not in London, UK)!
```

Original comment by `skarzhev...@gmail.com` on 13 Jun 2009 at 6:34

**Comment by GoogleCodeExporter** [comment]
```
Thanks skarzhevskyy. The latest snapshot works fine.
```

Original comment by `supd...@gmail.com` on 20 Jun 2009 at 12:11

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Using the latest code revision 3067, I'm getting this issue again.
```

Original comment by `cjbus...@gmail.com` on 31 Jan 2012 at 4:40
