### ISSUE TITLE
Mac OS X: Unable to establish RFCOMM connection (Failed to open baseban connection)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#72]
```
What steps will reproduce the problem?
1. (StreamConnection)
Connector.open("btspp://001E3B38E553:4;authenticate=false;encrypt=false;master=f
alse")
(Just an example) 
It also doesn't work if I discover the service from the device and try to
open a connection to it.


What is the expected output? What do you see instead?

The expected output would be to get the StreamConnection object to be able
to exchange data with the device. Instead, I get an exception:

javax.bluetooth.BluetoothConnectionException: Failed to open baseband
connection(2) [0x00000010]
at
com.intel.bluetooth.BluetoothStackOSX.connectionRfOpenClientConnectionImpl(Nativ
e
Method)
    at
com.intel.bluetooth.BluetoothStackOSX.connectionRfOpenClientConnection(Bluetooth
StackOSX.java:541)
    at
com.intel.bluetooth.BluetoothRFCommClientConnection.<init>(BluetoothRFCommClient
Connection.java:37)
    at
com.intel.bluetooth.MicroeditionConnector.openImpl(MicroeditionConnector.java:37
9)
    at
com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.java:162)
    at javax.microedition.io.Connector.open(Connector.java:83)
    at BTEndpointImpl.post(BTEndpointImpl.java:20)
    at RemoteDeviceDiscovery.main(RemoteDeviceDiscovery.java:20)

What BlueCove version are you using (include build number for SNAPSHOT)? On
what operating system and jvm? Is this 64-bit or 32-bit OS and jvm?

MAC OS X (10.5.6 Leopard), Java SE 1.5 (MAC OS X default), x86-32

Please provide any additional information below.
Please use "Attach a file" when uploading stack traces or other big files!

Attached find the complete trace (in debug mode)



```

Original issue reported on code.google.com by `franm...@gmail.com` on 16 Apr 2009 at 7:06

Attachments:
- [stack-trace-macos.txt](https://storage.googleapis.com/google-code-attachments/bluecove/issue-72/comment-0/stack-trace-macos.txt)

**Comment by GoogleCodeExporter** [comment]
```
All works fine with devices I used for tests.
Apparently this the problem with your Bluetooth dongle/devices. try different 
pair.
```

Original comment by `skarzhev...@gmail.com` on 16 Apr 2009 at 2:33
- Changed state: **WontFix**
