### ISSUE TITLE
Error with Bluecove in Linux

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dorkasdev/bluecove#99]
```
What steps will reproduce the problem?
1.Compiling has got no problem.
But when i want to run the project with the following command io got the
errors:
[reza@localhost blue]$ java -cp
./bluecove-2.1.0.jar:./bluecove-bluecove-gpl-2.1.0.jar RemoteDeviceDiscovery
Exception in thread "main" java.lang.NoClassDefFoundError:
RemoteDeviceDiscovery
Caused by: java.lang.ClassNotFoundException: RemoteDeviceDiscovery
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:336)
Could not find the main class: RemoteDeviceDiscovery. Program will exit.
```

Original issue reported on code.google.com by `sephirot...@gmail.com` on 8 Feb 2010 at 10:21

**Comment by GoogleCodeExporter** [comment]
```
RemoteDeviceDiscovery  is your class. Add it to classpath.

```

Original comment by `skarzhev...@gmail.com` on 31 Mar 2010 at 4:53
- Changed state: **Invalid**
